sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_REPO=continuous-report-delivery-rocker
  - EB_REGION="eu-west-1"
  - secure: Ni49j8XOzEHNWxd+2sNiVKoBDZL6ba9BE5rivxXh45XiTq0Vv6+n9TPiMXgKoNSAdSYxUgj7xkJmxBbj7pW54nKI+V444k39Ba7Eo6g6ALKJmP6TTpfl+zPnvhD7pihosJl853TM5N6c4dTMAcBMAgBXrdHkmmZg+mOTfoQLJWP0tGEWuahUhC2c3VqHghYmcDlMu+LVLHpC6asr18ZqYOFCDHSe9ENeNWQrgtUgll7CNVmVaxUpzQEWiRlEXh2SIpTp2g6foc830DKOpXWQDQnwtQEOXba8WSfLYnaHPF8tEWGcFOU1+2P2tCNqpYniV0eNH2TfDwHjUP3sB8i2wS2W7tSzBuBSQofGEnmVqNpI5748Mu4v6DmZ4zzY+88Wgaipsz8Mv9YF+1WnVG2ZtR90++XQKZkNQQ33krZH7WwGZKebPHKpUYFIwYNI6DyTWExWaODXR7yBwBX9VKwEH+3rV4k+2XlAW6uz44LxDjZWSIKncrPx1MPmRTC0VmRmice8yNyEUnuXXKcw6fphIrCV1f0tj4GtfKSOs059vaUX2ufz8SivDdHTwnZa/uT+zvez4kik2uoQpK6vrcb9d86hK40aWBmmh1e1o77atlGvEOjXxyPR5F0zl1FjYhde8ro14OSnWS7wWZHHudWxsIkH+4xhdO6VZmMWkFATt0M=
  - secure: Hhr+rj7kJfVrqJ/gs9fjTWt7lXdZF2834b0MnuOwnsmWxpfwq+Ho/8vBn3TKQrnG2RX+dfXdaG98Ob3WcGLlNO0FHXhUM/LgjBh/R+aYT6/GRI+ijOm7vBNmTOx3yHkQY9h+/ISJG4Bc0933e6y/nCpSRueYRZxmm6Dd1ousx39AUag4S3E7ZZOGxtFAL3OW3uMk79q9rpcpvhqKZB1380v4NOVaKrTChOZ/qSCNedJ1lfK7j/bSRoIjN/SRDUZC/9eo8/Ub7FWUAgyFmsBWw2+1fkWVcH1B2dVus5r7Wn5IZpngWUoAlsnTpvbSZJ5Ub67djytUUnSg+mu7yvsBMDtb2LWlLmARbthtvNHpyx+OCRwojn2DLK6TkrC9D1feZCiHjqeBNVcwqgmn67YytircIaBBq1vBHJJ3llEjeoHPpqtuDHTSTggRfxQOibtsIgtSk75HT2L0jVOMTom0WdqQnahwZiCHnWv8gLgFWNNKvbeXUBva7klM7quDscxe889M0kNnQdGhgiW6ADzlxLT9oCFTymQOqt3RKIC8AhBQP4Hzeburzdbq6bcv40xKSxakrWvcAuTSJ8gWY8DavcaF0DqI2PzOyWjqqDcLQgJgR0NYQ6e9cGciZ4qiJjnwtd2wXnsaYdqW4Qm6mjVkcGXdT99ismXf8Q1HwawaGZs=
  - secure: IeNzU9a8o769eRvOF4trJdMocsRfps3dT1+NhR5R8GQqDV4m2lRuahX0dCQMa0hQHYwnQHoN1pXvtLFpZomxcNVXh9wHpn2gYpDqvprJ/ibjo74gRDcpHzRqysjrrMQpi+ZV8YWUozKneympzKzNzSMVsP55s6Rr75ZmsN0R25qLTeo6QJlh1gSBtUFmPDZ1eeidLp89XujgxdIg7m93ykSL7gSBUk+8lHY2Slyi7kuBgrhAf3U3muLlb/lKsOmF9ZvpEnqP+lu9BsDVn4dhOaSetHYiofdRBflu6Fu6ewPlGSYP85EoK0HS+lt2SKRA2Ejs77DumFT1Gio8XjVA+5BsDhP+4Jd/FsrwdaJNLMRE49Lc6F3yxIA/mvBitY7jmpVaMj1qOVwp7YFtJK1y+8WkpUEbYoEqSmEGjAMzIQnAqcMXN8seY1uE198mfVnKsf0TdglUaOm6sqKU0WkMQZhXE4PWTWV7D0e5m7agYgyWozULBubb2cLYS67SE43qaDFC29r1pm1TkTHgiVBKz0XvSW8qje/CSVNgh7qSevJc3E5CWy9YNoBxwcDxtX0Jgmii6zOpDmqcaIwBXsslTTadPaQY3uz/MWr/Se+BuPFxf/onfUcyjQlrxXJEPrGXJNvOZV0xSlqBUA9lFQHfNidRzxd4O3hx3fZMVcP2DyM=
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- mkdir ~/.aws
- cp ./deploy/aws/* ~/.aws/
- echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
- echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
