sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_REPO=continuous-report-delivery-rocker
  - EB_REGION="eu-west-1"
  - secure: hCBIWJO8a2n2ed+Lf306od0qA/omy3UVPjVlqBar682xAXAC5YuNCKTS56XFlp7rsybR6mZILnq/ouRghOeRUiiz6aiRaSsMZkVXAic+2qYbVTy6Pm9fp/efLW7y5B8DXCcm3PEynQ5Q1YbxHZia8DFSkXEaw1/ieYbTMnZbdD/QawTyypgJksCuIzaRTVRffXqaA0tPSJdF8ne2G4Bl+FmFVGdwlEHdlBIZZzJMd1xEEYF2x4wZFwOT9FbcSW92/JFjRdcw+OE784n1bIsHx9/n/DwdvbXO1mgzlsRwGUbkF9XH5UCep1p+GBA4TU2wM6GrSqQIz04IePk28IdF46a8clsej1nz5UYLJDibevQxqK+z0ghrfpdXwtYTSAs4iO13TegS7LFTLH6txzZ63FTkIy0B3XsaB/0DusdMhCwqoMM+IxyebZovaR980dj7Dp6pP6b2RWEfjOvQZaVtKHMbUUJx7Tnt1LmR5W4oz0xnSxXNevObYsol+RPBTwpKttJ99JNGMlMNg5fbMxKUrhLsIfKnC44YjzRgy8fflWGb0hmUEwDmxoTGLua/WllMmA3fdhRKIoTM6gUH77QvAX44cGguxbVqlN7ClEi5PpFXNSXS6Kgq+Y/1w2ybZuNhKfl9BJOyJNMNzgQEwFeMQ9+8BsvDDFwVcGhPrblUOKA=
  - secure: wTlA7R0CpE+LQ/FIG+2dADdhGrILXMlfDygsvBoaJcHqf7lBbR9sI0gL3sNJ7pVCXY1szI16iX7qRp7+NqdibM80zCv4k8wDEjQo58TkMy8QGs2dh5An7FAlpCUd7C1/2nT6KRZhOxKY+9ZN5fA99nL2Fua/wjhd0aheu8AG9chf+5r1NfwetDO8K1Hu3s4UASaTfVCQpwDL9+2ykngUJbcYlJhVvedJxkQK0YqOgrhYzeSFzibyYGt1aOe1LCcHd8uyiemtAvel+eTg8fQMQju6rxFD1wyw2w3nrhqoqUNdWfxJxbokZzf6xMP7mAwC7JjzwHHqrvXj09tnf2BEciSt1jmfoQvNOCsms4dV7mFh0EHmHSpKtJduBFqG8UZ3UJvmY8S1Zehrt2G2/OxPlYgctktbVOxWXawJg4Ytq0A1YW3mnDDiEZfxtT0mizFbNHXM+QWo4k9jA6/Z/SnjqPjRJ5kWI0eWzDWiJdAnHDyMiFpsSuhVpRP86CF5400QvE67PQDo66gYxWuxLKs7uhXoGlvzQaNy9ioAGi58taN02KsC45GsSTxhEABGlMJGVodQyeG8BC1Jvp/dcw8IH//Y+vyvhGcW2BJBVfljMVlX02/vZNm6iW31MZ/FfcknTSKdhTiRA/xeqJdg3QT6x+huLhVvPxleihemaRvuGRA=
  - secure: q6atj2gu4yKWu42TXTOzcfSgdsn5tqHO0gskXcwIR2l8BucT2jxamUGyjFPszPdkGNgFndn3zh6Gd4OWs5Cn0Tp2ZnxvhADknFcxVLgu94s6tuxjTMVcp8PfDXU9Qy2iZFuZPbjjBY14mHY+xGQERcSSkF3rVjB8vNmP11nBCjnOWQMZ4873xRdrzHvr8jkz8ZKA0qvfh2RCclDMpXGCLJTqwu5FfKAxzZN+lk47SjhJjctFSuXUzXmWAG+D6URx6XBg6SD8WP7hy9wL6WwL2cM7uRvGzNrkFOR9zWibSrIEIZY1/isBOuivDkHjRP+xTzhsYwIvXAym61nezPIXTuZqFO4nf08B5iZc3Y4FK1gIbZ9QhYJFmm6ln2NiOYWbP3z1A7ZdgZvwr2O/PjB4dWzeW3Z9X46ePffOVytmfSIni50Mqr8GnoAlGVZ0VrIDDJjA0dXfc3xZsoKn3Q/s5JowwIjap82d7DoPZZ8skEX6rEnEMnElRZUDAcFh3npdKRQXzSqd0biy3FtGq1ETsWc5HgHV8sXT9SzbVIii2Gy6ZXVf9EMIWyO8hfo1PyUBd895ftvN9aYRlKDjmm8N586oR+KiYjggjzaBcXEuVoe87g39js0uTBdB8xgOODfmb9yaYJEo/khU6Q7Ezz2u7QvHAMYkVkF6ntuXkWfEYv8=
install:
- pip install awscli 
- export PATH=$PATH:$HOME/.local/bin
- cp ~/deploy/docker-credential-ecr-login ~/.local/bin/docker-credential-ecr-login
- chmod +x ~/.local/bin/docker-credential-ecr-login
- mkdir ~/.aws
- cp ./deploy/aws/* ~/.aws/
- echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
- echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
