sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_REPO=continuous-report-delivery-rocker
  - EB_REGION="eu-west-1"
  - secure: AWS_ACCOUNT_ID
  - secure: AWS_ACCESS_KEY_ID
  - secure: AWS_SECRET_ACCESS_KEY
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
- mkdir ~/.aws
- cp ./.aws/config ~/.aws/config
- cp ./.aws/credentials ~/.aws/credentials
- echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
- echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
